#pragma once

#include "Global.hpp"

#include "Texture.hpp"
#include "Nodes/BMPinput.hpp"
#include "Nodes/CanvasNode.hpp"
#include "NodeSystem/Node.hpp"
#include "NodeSystem/NodeData.hpp"
#include "NodeSystem/NodeDataImage.hpp"
#include "NodeSystem/NodeDataInt.hpp"
#include "NodeSystem/NodeDataMonochrome.hpp"
#include "NodeSystem/NodeInput.hpp"
#include "NodeSystem/NodeInputImage.hpp"
#include "NodeSystem/NodeInputInt.hpp"
#include "NodeSystem/NodeInputMonochrome.hpp"
#include "NodeSystem/NodeOutput.hpp"
#include "NodeSystem/NodeOutputImage.hpp"
#include "NodeSystem/NodeOutputInt.hpp"
#include "NodeSystem/NodeOutputMonochrome.hpp"
#include "NodeSystem/RowSelector.hpp"
#include "Widgets/Canvas.hpp"
#include "Widgets/NodeEditor.hpp"
